// Code generated by entc, DO NOT EDIT.

package schemetype

const (
	// Label holds the string label denoting the schemetype type in the database.
	Label = "scheme_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSchemeTypeName holds the string denoting the schemetype_name field in the database.
	FieldSchemeTypeName = "scheme_type_name"

	// EdgeSchemeTypeCoveredPerson holds the string denoting the schemetype_coveredperson edge name in mutations.
	EdgeSchemeTypeCoveredPerson = "SchemeType_CoveredPerson"

	// Table holds the table name of the schemetype in the database.
	Table = "scheme_types"
	// SchemeTypeCoveredPersonTable is the table the holds the SchemeType_CoveredPerson relation/edge.
	SchemeTypeCoveredPersonTable = "covered_persons"
	// SchemeTypeCoveredPersonInverseTable is the table name for the CoveredPerson entity.
	// It exists in this package in order to avoid circular dependency with the "coveredperson" package.
	SchemeTypeCoveredPersonInverseTable = "covered_persons"
	// SchemeTypeCoveredPersonColumn is the table column denoting the SchemeType_CoveredPerson relation/edge.
	SchemeTypeCoveredPersonColumn = "SchemeType_id"
)

// Columns holds all SQL columns for schemetype fields.
var Columns = []string{
	FieldID,
	FieldSchemeTypeName,
}

var (
	// SchemeTypeNameValidator is a validator for the "SchemeType_Name" field. It is called by the builders before save.
	SchemeTypeNameValidator func(string) error
)
