// Code generated by entc, DO NOT EDIT.

package schemetype

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/sut63/team08/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// SchemeTypeName applies equality check predicate on the "SchemeType_Name" field. It's identical to SchemeTypeNameEQ.
func SchemeTypeName(v string) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSchemeTypeName), v))
	})
}

// SchemeTypeNameEQ applies the EQ predicate on the "SchemeType_Name" field.
func SchemeTypeNameEQ(v string) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSchemeTypeName), v))
	})
}

// SchemeTypeNameNEQ applies the NEQ predicate on the "SchemeType_Name" field.
func SchemeTypeNameNEQ(v string) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSchemeTypeName), v))
	})
}

// SchemeTypeNameIn applies the In predicate on the "SchemeType_Name" field.
func SchemeTypeNameIn(vs ...string) predicate.SchemeType {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SchemeType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSchemeTypeName), v...))
	})
}

// SchemeTypeNameNotIn applies the NotIn predicate on the "SchemeType_Name" field.
func SchemeTypeNameNotIn(vs ...string) predicate.SchemeType {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SchemeType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSchemeTypeName), v...))
	})
}

// SchemeTypeNameGT applies the GT predicate on the "SchemeType_Name" field.
func SchemeTypeNameGT(v string) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSchemeTypeName), v))
	})
}

// SchemeTypeNameGTE applies the GTE predicate on the "SchemeType_Name" field.
func SchemeTypeNameGTE(v string) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSchemeTypeName), v))
	})
}

// SchemeTypeNameLT applies the LT predicate on the "SchemeType_Name" field.
func SchemeTypeNameLT(v string) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSchemeTypeName), v))
	})
}

// SchemeTypeNameLTE applies the LTE predicate on the "SchemeType_Name" field.
func SchemeTypeNameLTE(v string) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSchemeTypeName), v))
	})
}

// SchemeTypeNameContains applies the Contains predicate on the "SchemeType_Name" field.
func SchemeTypeNameContains(v string) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSchemeTypeName), v))
	})
}

// SchemeTypeNameHasPrefix applies the HasPrefix predicate on the "SchemeType_Name" field.
func SchemeTypeNameHasPrefix(v string) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSchemeTypeName), v))
	})
}

// SchemeTypeNameHasSuffix applies the HasSuffix predicate on the "SchemeType_Name" field.
func SchemeTypeNameHasSuffix(v string) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSchemeTypeName), v))
	})
}

// SchemeTypeNameEqualFold applies the EqualFold predicate on the "SchemeType_Name" field.
func SchemeTypeNameEqualFold(v string) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSchemeTypeName), v))
	})
}

// SchemeTypeNameContainsFold applies the ContainsFold predicate on the "SchemeType_Name" field.
func SchemeTypeNameContainsFold(v string) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSchemeTypeName), v))
	})
}

// HasSchemeTypeCoveredPerson applies the HasEdge predicate on the "SchemeType_CoveredPerson" edge.
func HasSchemeTypeCoveredPerson() predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SchemeTypeCoveredPersonTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SchemeTypeCoveredPersonTable, SchemeTypeCoveredPersonColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSchemeTypeCoveredPersonWith applies the HasEdge predicate on the "SchemeType_CoveredPerson" edge with a given conditions (other predicates).
func HasSchemeTypeCoveredPersonWith(preds ...predicate.CoveredPerson) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SchemeTypeCoveredPersonInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SchemeTypeCoveredPersonTable, SchemeTypeCoveredPersonColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.SchemeType) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.SchemeType) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SchemeType) predicate.SchemeType {
	return predicate.SchemeType(func(s *sql.Selector) {
		p(s.Not())
	})
}
