// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/sut63/team08/ent/bloodtype"
)

// Bloodtype is the model entity for the Bloodtype schema.
type Bloodtype struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// BTname holds the value of the "BTname" field.
	BTname string `json:"BTname,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BloodtypeQuery when eager-loading is set.
	Edges BloodtypeEdges `json:"edges"`
}

// BloodtypeEdges holds the relations/edges for other nodes in the graph.
type BloodtypeEdges struct {
	// Frombloodtype holds the value of the frombloodtype edge.
	Frombloodtype []*Patient
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// FrombloodtypeOrErr returns the Frombloodtype value or an error if the edge
// was not loaded in eager-loading.
func (e BloodtypeEdges) FrombloodtypeOrErr() ([]*Patient, error) {
	if e.loadedTypes[0] {
		return e.Frombloodtype, nil
	}
	return nil, &NotLoadedError{edge: "frombloodtype"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Bloodtype) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // BTname
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Bloodtype fields.
func (b *Bloodtype) assignValues(values ...interface{}) error {
	if m, n := len(values), len(bloodtype.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	b.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field BTname", values[0])
	} else if value.Valid {
		b.BTname = value.String
	}
	return nil
}

// QueryFrombloodtype queries the frombloodtype edge of the Bloodtype.
func (b *Bloodtype) QueryFrombloodtype() *PatientQuery {
	return (&BloodtypeClient{config: b.config}).QueryFrombloodtype(b)
}

// Update returns a builder for updating this Bloodtype.
// Note that, you need to call Bloodtype.Unwrap() before calling this method, if this Bloodtype
// was returned from a transaction, and the transaction was committed or rolled back.
func (b *Bloodtype) Update() *BloodtypeUpdateOne {
	return (&BloodtypeClient{config: b.config}).UpdateOne(b)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (b *Bloodtype) Unwrap() *Bloodtype {
	tx, ok := b.config.driver.(*txDriver)
	if !ok {
		panic("ent: Bloodtype is not a transactional entity")
	}
	b.config.driver = tx.drv
	return b
}

// String implements the fmt.Stringer.
func (b *Bloodtype) String() string {
	var builder strings.Builder
	builder.WriteString("Bloodtype(")
	builder.WriteString(fmt.Sprintf("id=%v", b.ID))
	builder.WriteString(", BTname=")
	builder.WriteString(b.BTname)
	builder.WriteByte(')')
	return builder.String()
}

// Bloodtypes is a parsable slice of Bloodtype.
type Bloodtypes []*Bloodtype

func (b Bloodtypes) config(cfg config) {
	for _i := range b {
		b[_i].config = cfg
	}
}
