// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/sut63/team08/ent/certificate"
	"github.com/sut63/team08/ent/coveredperson"
	"github.com/sut63/team08/ent/predicate"
)

// CertificateUpdate is the builder for updating Certificate entities.
type CertificateUpdate struct {
	config
	hooks      []Hook
	mutation   *CertificateMutation
	predicates []predicate.Certificate
}

// Where adds a new predicate for the builder.
func (cu *CertificateUpdate) Where(ps ...predicate.Certificate) *CertificateUpdate {
	cu.predicates = append(cu.predicates, ps...)
	return cu
}

// SetCertificateName sets the Certificate_Name field.
func (cu *CertificateUpdate) SetCertificateName(s string) *CertificateUpdate {
	cu.mutation.SetCertificateName(s)
	return cu
}

// AddCertificateCoveredPersonIDs adds the Certificate_CoveredPerson edge to CoveredPerson by ids.
func (cu *CertificateUpdate) AddCertificateCoveredPersonIDs(ids ...int) *CertificateUpdate {
	cu.mutation.AddCertificateCoveredPersonIDs(ids...)
	return cu
}

// AddCertificateCoveredPerson adds the Certificate_CoveredPerson edges to CoveredPerson.
func (cu *CertificateUpdate) AddCertificateCoveredPerson(c ...*CoveredPerson) *CertificateUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.AddCertificateCoveredPersonIDs(ids...)
}

// Mutation returns the CertificateMutation object of the builder.
func (cu *CertificateUpdate) Mutation() *CertificateMutation {
	return cu.mutation
}

// RemoveCertificateCoveredPersonIDs removes the Certificate_CoveredPerson edge to CoveredPerson by ids.
func (cu *CertificateUpdate) RemoveCertificateCoveredPersonIDs(ids ...int) *CertificateUpdate {
	cu.mutation.RemoveCertificateCoveredPersonIDs(ids...)
	return cu
}

// RemoveCertificateCoveredPerson removes Certificate_CoveredPerson edges to CoveredPerson.
func (cu *CertificateUpdate) RemoveCertificateCoveredPerson(c ...*CoveredPerson) *CertificateUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.RemoveCertificateCoveredPersonIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (cu *CertificateUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := cu.mutation.CertificateName(); ok {
		if err := certificate.CertificateNameValidator(v); err != nil {
			return 0, &ValidationError{Name: "Certificate_Name", err: fmt.Errorf("ent: validator failed for field \"Certificate_Name\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CertificateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CertificateUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CertificateUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CertificateUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *CertificateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   certificate.Table,
			Columns: certificate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: certificate.FieldID,
			},
		},
	}
	if ps := cu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.CertificateName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: certificate.FieldCertificateName,
		})
	}
	if nodes := cu.mutation.RemovedCertificateCoveredPersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.CertificateCoveredPersonTable,
			Columns: []string{certificate.CertificateCoveredPersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: coveredperson.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.CertificateCoveredPersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.CertificateCoveredPersonTable,
			Columns: []string{certificate.CertificateCoveredPersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: coveredperson.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{certificate.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// CertificateUpdateOne is the builder for updating a single Certificate entity.
type CertificateUpdateOne struct {
	config
	hooks    []Hook
	mutation *CertificateMutation
}

// SetCertificateName sets the Certificate_Name field.
func (cuo *CertificateUpdateOne) SetCertificateName(s string) *CertificateUpdateOne {
	cuo.mutation.SetCertificateName(s)
	return cuo
}

// AddCertificateCoveredPersonIDs adds the Certificate_CoveredPerson edge to CoveredPerson by ids.
func (cuo *CertificateUpdateOne) AddCertificateCoveredPersonIDs(ids ...int) *CertificateUpdateOne {
	cuo.mutation.AddCertificateCoveredPersonIDs(ids...)
	return cuo
}

// AddCertificateCoveredPerson adds the Certificate_CoveredPerson edges to CoveredPerson.
func (cuo *CertificateUpdateOne) AddCertificateCoveredPerson(c ...*CoveredPerson) *CertificateUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.AddCertificateCoveredPersonIDs(ids...)
}

// Mutation returns the CertificateMutation object of the builder.
func (cuo *CertificateUpdateOne) Mutation() *CertificateMutation {
	return cuo.mutation
}

// RemoveCertificateCoveredPersonIDs removes the Certificate_CoveredPerson edge to CoveredPerson by ids.
func (cuo *CertificateUpdateOne) RemoveCertificateCoveredPersonIDs(ids ...int) *CertificateUpdateOne {
	cuo.mutation.RemoveCertificateCoveredPersonIDs(ids...)
	return cuo
}

// RemoveCertificateCoveredPerson removes Certificate_CoveredPerson edges to CoveredPerson.
func (cuo *CertificateUpdateOne) RemoveCertificateCoveredPerson(c ...*CoveredPerson) *CertificateUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.RemoveCertificateCoveredPersonIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (cuo *CertificateUpdateOne) Save(ctx context.Context) (*Certificate, error) {
	if v, ok := cuo.mutation.CertificateName(); ok {
		if err := certificate.CertificateNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Certificate_Name", err: fmt.Errorf("ent: validator failed for field \"Certificate_Name\": %w", err)}
		}
	}

	var (
		err  error
		node *Certificate
	)
	if len(cuo.hooks) == 0 {
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CertificateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CertificateUpdateOne) SaveX(ctx context.Context) *Certificate {
	c, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return c
}

// Exec executes the query on the entity.
func (cuo *CertificateUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CertificateUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *CertificateUpdateOne) sqlSave(ctx context.Context) (c *Certificate, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   certificate.Table,
			Columns: certificate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: certificate.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Certificate.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := cuo.mutation.CertificateName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: certificate.FieldCertificateName,
		})
	}
	if nodes := cuo.mutation.RemovedCertificateCoveredPersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.CertificateCoveredPersonTable,
			Columns: []string{certificate.CertificateCoveredPersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: coveredperson.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.CertificateCoveredPersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.CertificateCoveredPersonTable,
			Columns: []string{certificate.CertificateCoveredPersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: coveredperson.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	c = &Certificate{config: cuo.config}
	_spec.Assign = c.assignValues
	_spec.ScanValues = c.scanValues()
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{certificate.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return c, nil
}
