// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/sut63/team08/ent/predicate"
	"github.com/sut63/team08/ent/room"
	"github.com/sut63/team08/ent/roomtype"
)

// RoomtypeUpdate is the builder for updating Roomtype entities.
type RoomtypeUpdate struct {
	config
	hooks      []Hook
	mutation   *RoomtypeMutation
	predicates []predicate.Roomtype
}

// Where adds a new predicate for the builder.
func (ru *RoomtypeUpdate) Where(ps ...predicate.Roomtype) *RoomtypeUpdate {
	ru.predicates = append(ru.predicates, ps...)
	return ru
}

// SetName sets the name field.
func (ru *RoomtypeUpdate) SetName(s string) *RoomtypeUpdate {
	ru.mutation.SetName(s)
	return ru
}

// SetBathroom sets the bathroom field.
func (ru *RoomtypeUpdate) SetBathroom(i int) *RoomtypeUpdate {
	ru.mutation.ResetBathroom()
	ru.mutation.SetBathroom(i)
	return ru
}

// AddBathroom adds i to bathroom.
func (ru *RoomtypeUpdate) AddBathroom(i int) *RoomtypeUpdate {
	ru.mutation.AddBathroom(i)
	return ru
}

// SetToilets sets the toilets field.
func (ru *RoomtypeUpdate) SetToilets(i int) *RoomtypeUpdate {
	ru.mutation.ResetToilets()
	ru.mutation.SetToilets(i)
	return ru
}

// AddToilets adds i to toilets.
func (ru *RoomtypeUpdate) AddToilets(i int) *RoomtypeUpdate {
	ru.mutation.AddToilets(i)
	return ru
}

// SetAreasize sets the areasize field.
func (ru *RoomtypeUpdate) SetAreasize(f float64) *RoomtypeUpdate {
	ru.mutation.ResetAreasize()
	ru.mutation.SetAreasize(f)
	return ru
}

// AddAreasize adds f to areasize.
func (ru *RoomtypeUpdate) AddAreasize(f float64) *RoomtypeUpdate {
	ru.mutation.AddAreasize(f)
	return ru
}

// SetEtc sets the etc field.
func (ru *RoomtypeUpdate) SetEtc(s string) *RoomtypeUpdate {
	ru.mutation.SetEtc(s)
	return ru
}

// AddRoomIDs adds the rooms edge to Room by ids.
func (ru *RoomtypeUpdate) AddRoomIDs(ids ...int) *RoomtypeUpdate {
	ru.mutation.AddRoomIDs(ids...)
	return ru
}

// AddRooms adds the rooms edges to Room.
func (ru *RoomtypeUpdate) AddRooms(r ...*Room) *RoomtypeUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.AddRoomIDs(ids...)
}

// Mutation returns the RoomtypeMutation object of the builder.
func (ru *RoomtypeUpdate) Mutation() *RoomtypeMutation {
	return ru.mutation
}

// RemoveRoomIDs removes the rooms edge to Room by ids.
func (ru *RoomtypeUpdate) RemoveRoomIDs(ids ...int) *RoomtypeUpdate {
	ru.mutation.RemoveRoomIDs(ids...)
	return ru
}

// RemoveRooms removes rooms edges to Room.
func (ru *RoomtypeUpdate) RemoveRooms(r ...*Room) *RoomtypeUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.RemoveRoomIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (ru *RoomtypeUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := ru.mutation.Name(); ok {
		if err := roomtype.NameValidator(v); err != nil {
			return 0, &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if v, ok := ru.mutation.Areasize(); ok {
		if err := roomtype.AreasizeValidator(v); err != nil {
			return 0, &ValidationError{Name: "areasize", err: fmt.Errorf("ent: validator failed for field \"areasize\": %w", err)}
		}
	}
	if v, ok := ru.mutation.Etc(); ok {
		if err := roomtype.EtcValidator(v); err != nil {
			return 0, &ValidationError{Name: "etc", err: fmt.Errorf("ent: validator failed for field \"etc\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(ru.hooks) == 0 {
		affected, err = ru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomtypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ru.mutation = mutation
			affected, err = ru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ru.hooks) - 1; i >= 0; i-- {
			mut = ru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RoomtypeUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RoomtypeUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RoomtypeUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RoomtypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   roomtype.Table,
			Columns: roomtype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roomtype.FieldID,
			},
		},
	}
	if ps := ru.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: roomtype.FieldName,
		})
	}
	if value, ok := ru.mutation.Bathroom(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roomtype.FieldBathroom,
		})
	}
	if value, ok := ru.mutation.AddedBathroom(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roomtype.FieldBathroom,
		})
	}
	if value, ok := ru.mutation.Toilets(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roomtype.FieldToilets,
		})
	}
	if value, ok := ru.mutation.AddedToilets(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roomtype.FieldToilets,
		})
	}
	if value, ok := ru.mutation.Areasize(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: roomtype.FieldAreasize,
		})
	}
	if value, ok := ru.mutation.AddedAreasize(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: roomtype.FieldAreasize,
		})
	}
	if value, ok := ru.mutation.Etc(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: roomtype.FieldEtc,
		})
	}
	if nodes := ru.mutation.RemovedRoomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roomtype.RoomsTable,
			Columns: []string{roomtype.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RoomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roomtype.RoomsTable,
			Columns: []string{roomtype.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roomtype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// RoomtypeUpdateOne is the builder for updating a single Roomtype entity.
type RoomtypeUpdateOne struct {
	config
	hooks    []Hook
	mutation *RoomtypeMutation
}

// SetName sets the name field.
func (ruo *RoomtypeUpdateOne) SetName(s string) *RoomtypeUpdateOne {
	ruo.mutation.SetName(s)
	return ruo
}

// SetBathroom sets the bathroom field.
func (ruo *RoomtypeUpdateOne) SetBathroom(i int) *RoomtypeUpdateOne {
	ruo.mutation.ResetBathroom()
	ruo.mutation.SetBathroom(i)
	return ruo
}

// AddBathroom adds i to bathroom.
func (ruo *RoomtypeUpdateOne) AddBathroom(i int) *RoomtypeUpdateOne {
	ruo.mutation.AddBathroom(i)
	return ruo
}

// SetToilets sets the toilets field.
func (ruo *RoomtypeUpdateOne) SetToilets(i int) *RoomtypeUpdateOne {
	ruo.mutation.ResetToilets()
	ruo.mutation.SetToilets(i)
	return ruo
}

// AddToilets adds i to toilets.
func (ruo *RoomtypeUpdateOne) AddToilets(i int) *RoomtypeUpdateOne {
	ruo.mutation.AddToilets(i)
	return ruo
}

// SetAreasize sets the areasize field.
func (ruo *RoomtypeUpdateOne) SetAreasize(f float64) *RoomtypeUpdateOne {
	ruo.mutation.ResetAreasize()
	ruo.mutation.SetAreasize(f)
	return ruo
}

// AddAreasize adds f to areasize.
func (ruo *RoomtypeUpdateOne) AddAreasize(f float64) *RoomtypeUpdateOne {
	ruo.mutation.AddAreasize(f)
	return ruo
}

// SetEtc sets the etc field.
func (ruo *RoomtypeUpdateOne) SetEtc(s string) *RoomtypeUpdateOne {
	ruo.mutation.SetEtc(s)
	return ruo
}

// AddRoomIDs adds the rooms edge to Room by ids.
func (ruo *RoomtypeUpdateOne) AddRoomIDs(ids ...int) *RoomtypeUpdateOne {
	ruo.mutation.AddRoomIDs(ids...)
	return ruo
}

// AddRooms adds the rooms edges to Room.
func (ruo *RoomtypeUpdateOne) AddRooms(r ...*Room) *RoomtypeUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.AddRoomIDs(ids...)
}

// Mutation returns the RoomtypeMutation object of the builder.
func (ruo *RoomtypeUpdateOne) Mutation() *RoomtypeMutation {
	return ruo.mutation
}

// RemoveRoomIDs removes the rooms edge to Room by ids.
func (ruo *RoomtypeUpdateOne) RemoveRoomIDs(ids ...int) *RoomtypeUpdateOne {
	ruo.mutation.RemoveRoomIDs(ids...)
	return ruo
}

// RemoveRooms removes rooms edges to Room.
func (ruo *RoomtypeUpdateOne) RemoveRooms(r ...*Room) *RoomtypeUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.RemoveRoomIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (ruo *RoomtypeUpdateOne) Save(ctx context.Context) (*Roomtype, error) {
	if v, ok := ruo.mutation.Name(); ok {
		if err := roomtype.NameValidator(v); err != nil {
			return nil, &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if v, ok := ruo.mutation.Areasize(); ok {
		if err := roomtype.AreasizeValidator(v); err != nil {
			return nil, &ValidationError{Name: "areasize", err: fmt.Errorf("ent: validator failed for field \"areasize\": %w", err)}
		}
	}
	if v, ok := ruo.mutation.Etc(); ok {
		if err := roomtype.EtcValidator(v); err != nil {
			return nil, &ValidationError{Name: "etc", err: fmt.Errorf("ent: validator failed for field \"etc\": %w", err)}
		}
	}

	var (
		err  error
		node *Roomtype
	)
	if len(ruo.hooks) == 0 {
		node, err = ruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomtypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ruo.mutation = mutation
			node, err = ruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ruo.hooks) - 1; i >= 0; i-- {
			mut = ruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RoomtypeUpdateOne) SaveX(ctx context.Context) *Roomtype {
	r, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return r
}

// Exec executes the query on the entity.
func (ruo *RoomtypeUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RoomtypeUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RoomtypeUpdateOne) sqlSave(ctx context.Context) (r *Roomtype, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   roomtype.Table,
			Columns: roomtype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roomtype.FieldID,
			},
		},
	}
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Roomtype.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := ruo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: roomtype.FieldName,
		})
	}
	if value, ok := ruo.mutation.Bathroom(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roomtype.FieldBathroom,
		})
	}
	if value, ok := ruo.mutation.AddedBathroom(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roomtype.FieldBathroom,
		})
	}
	if value, ok := ruo.mutation.Toilets(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roomtype.FieldToilets,
		})
	}
	if value, ok := ruo.mutation.AddedToilets(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roomtype.FieldToilets,
		})
	}
	if value, ok := ruo.mutation.Areasize(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: roomtype.FieldAreasize,
		})
	}
	if value, ok := ruo.mutation.AddedAreasize(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: roomtype.FieldAreasize,
		})
	}
	if value, ok := ruo.mutation.Etc(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: roomtype.FieldEtc,
		})
	}
	if nodes := ruo.mutation.RemovedRoomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roomtype.RoomsTable,
			Columns: []string{roomtype.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RoomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roomtype.RoomsTable,
			Columns: []string{roomtype.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	r = &Roomtype{config: ruo.config}
	_spec.Assign = r.assignValues
	_spec.ScanValues = r.scanValues()
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roomtype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return r, nil
}
