// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/sut63/team08/ent/operativerecord"
	"github.com/sut63/team08/ent/tool"
)

// ToolCreate is the builder for creating a Tool entity.
type ToolCreate struct {
	config
	mutation *ToolMutation
	hooks    []Hook
}

// SetToolName sets the Tool_Name field.
func (tc *ToolCreate) SetToolName(s string) *ToolCreate {
	tc.mutation.SetToolName(s)
	return tc
}

// AddToolOperativerecordIDs adds the Tool_Operativerecord edge to Operativerecord by ids.
func (tc *ToolCreate) AddToolOperativerecordIDs(ids ...int) *ToolCreate {
	tc.mutation.AddToolOperativerecordIDs(ids...)
	return tc
}

// AddToolOperativerecord adds the Tool_Operativerecord edges to Operativerecord.
func (tc *ToolCreate) AddToolOperativerecord(o ...*Operativerecord) *ToolCreate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return tc.AddToolOperativerecordIDs(ids...)
}

// Mutation returns the ToolMutation object of the builder.
func (tc *ToolCreate) Mutation() *ToolMutation {
	return tc.mutation
}

// Save creates the Tool in the database.
func (tc *ToolCreate) Save(ctx context.Context) (*Tool, error) {
	if _, ok := tc.mutation.ToolName(); !ok {
		return nil, &ValidationError{Name: "Tool_Name", err: errors.New("ent: missing required field \"Tool_Name\"")}
	}
	if v, ok := tc.mutation.ToolName(); ok {
		if err := tool.ToolNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Tool_Name", err: fmt.Errorf("ent: validator failed for field \"Tool_Name\": %w", err)}
		}
	}
	var (
		err  error
		node *Tool
	)
	if len(tc.hooks) == 0 {
		node, err = tc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ToolMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tc.mutation = mutation
			node, err = tc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tc.hooks) - 1; i >= 0; i-- {
			mut = tc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tc *ToolCreate) SaveX(ctx context.Context) *Tool {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tc *ToolCreate) sqlSave(ctx context.Context) (*Tool, error) {
	t, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	t.ID = int(id)
	return t, nil
}

func (tc *ToolCreate) createSpec() (*Tool, *sqlgraph.CreateSpec) {
	var (
		t     = &Tool{config: tc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: tool.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tool.FieldID,
			},
		}
	)
	if value, ok := tc.mutation.ToolName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tool.FieldToolName,
		})
		t.ToolName = value
	}
	if nodes := tc.mutation.ToolOperativerecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tool.ToolOperativerecordTable,
			Columns: []string{tool.ToolOperativerecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: operativerecord.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return t, _spec
}
