// Code generated by entc, DO NOT EDIT.

package prefix

const (
	// Label holds the string label denoting the prefix type in the database.
	Label = "prefix"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPname holds the string denoting the pname field in the database.
	FieldPname = "pname"

	// EdgeFromprefix holds the string denoting the fromprefix edge name in mutations.
	EdgeFromprefix = "fromprefix"

	// Table holds the table name of the prefix in the database.
	Table = "prefixes"
	// FromprefixTable is the table the holds the fromprefix relation/edge.
	FromprefixTable = "patients"
	// FromprefixInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	FromprefixInverseTable = "patients"
	// FromprefixColumn is the table column denoting the fromprefix relation/edge.
	FromprefixColumn = "prefix_id"
)

// Columns holds all SQL columns for prefix fields.
var Columns = []string{
	FieldID,
	FieldPname,
}

var (
	// PnameValidator is a validator for the "Pname" field. It is called by the builders before save.
	PnameValidator func(string) error
)
