// Code generated by entc, DO NOT EDIT.

package operativerecord

import (
	"time"
)

const (
	// Label holds the string label denoting the operativerecord type in the database.
	Label = "operativerecord"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOperativeTime holds the string denoting the operativetime field in the database.
	FieldOperativeTime = "operative_time"

	// EdgeExaminationroom holds the string denoting the examinationroom edge name in mutations.
	EdgeExaminationroom = "Examinationroom"
	// EdgeNurse holds the string denoting the nurse edge name in mutations.
	EdgeNurse = "Nurse"
	// EdgeOperative holds the string denoting the operative edge name in mutations.
	EdgeOperative = "Operative"
	// EdgeTool holds the string denoting the tool edge name in mutations.
	EdgeTool = "Tool"

	// Table holds the table name of the operativerecord in the database.
	Table = "operativerecords"
	// ExaminationroomTable is the table the holds the Examinationroom relation/edge.
	ExaminationroomTable = "operativerecords"
	// ExaminationroomInverseTable is the table name for the Examinationroom entity.
	// It exists in this package in order to avoid circular dependency with the "examinationroom" package.
	ExaminationroomInverseTable = "examinationrooms"
	// ExaminationroomColumn is the table column denoting the Examinationroom relation/edge.
	ExaminationroomColumn = "Examinationroom_id"
	// NurseTable is the table the holds the Nurse relation/edge.
	NurseTable = "operativerecords"
	// NurseInverseTable is the table name for the Nurse entity.
	// It exists in this package in order to avoid circular dependency with the "nurse" package.
	NurseInverseTable = "nurses"
	// NurseColumn is the table column denoting the Nurse relation/edge.
	NurseColumn = "Nurse_id"
	// OperativeTable is the table the holds the Operative relation/edge.
	OperativeTable = "operativerecords"
	// OperativeInverseTable is the table name for the Operative entity.
	// It exists in this package in order to avoid circular dependency with the "operative" package.
	OperativeInverseTable = "operatives"
	// OperativeColumn is the table column denoting the Operative relation/edge.
	OperativeColumn = "Operative_id"
	// ToolTable is the table the holds the Tool relation/edge.
	ToolTable = "operativerecords"
	// ToolInverseTable is the table name for the Tool entity.
	// It exists in this package in order to avoid circular dependency with the "tool" package.
	ToolInverseTable = "tools"
	// ToolColumn is the table column denoting the Tool relation/edge.
	ToolColumn = "Tool_id"
)

// Columns holds all SQL columns for operativerecord fields.
var Columns = []string{
	FieldID,
	FieldOperativeTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Operativerecord type.
var ForeignKeys = []string{
	"Examinationroom_id",
	"Nurse_id",
	"Operative_id",
	"Tool_id",
}

var (
	// DefaultOperativeTime holds the default value on creation for the OperativeTime field.
	DefaultOperativeTime func() time.Time
)
