/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersPrescription
 */
export interface ControllersPrescription {
    /**
     * 
     * @type {string}
     * @memberof ControllersPrescription
     */
    added?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersPrescription
     */
    doctor?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPrescription
     */
    drug?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersPrescription
     */
    note?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersPrescription
     */
    nurse?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPrescription
     */
    patient?: number;
}

export function ControllersPrescriptionFromJSON(json: any): ControllersPrescription {
    return ControllersPrescriptionFromJSONTyped(json, false);
}

export function ControllersPrescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersPrescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'added': !exists(json, 'added') ? undefined : json['added'],
        'doctor': !exists(json, 'doctor') ? undefined : json['doctor'],
        'drug': !exists(json, 'drug') ? undefined : json['drug'],
        'note': !exists(json, 'note') ? undefined : json['note'],
        'nurse': !exists(json, 'nurse') ? undefined : json['nurse'],
        'patient': !exists(json, 'patient') ? undefined : json['patient'],
    };
}

export function ControllersPrescriptionToJSON(value?: ControllersPrescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'added': value.added,
        'doctor': value.doctor,
        'drug': value.drug,
        'note': value.note,
        'nurse': value.nurse,
        'patient': value.patient,
    };
}


