/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersRent
 */
export interface ControllersRent {
    /**
     * 
     * @type {string}
     * @memberof ControllersRent
     */
    added?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersRent
     */
    kinName?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersRent
     */
    kinTel?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersRent
     */
    nurse?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersRent
     */
    patient?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersRent
     */
    rentID?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersRent
     */
    room?: number;
}

export function ControllersRentFromJSON(json: any): ControllersRent {
    return ControllersRentFromJSONTyped(json, false);
}

export function ControllersRentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersRent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'added': !exists(json, 'added') ? undefined : json['added'],
        'kinName': !exists(json, 'kinName') ? undefined : json['kinName'],
        'kinTel': !exists(json, 'kinTel') ? undefined : json['kinTel'],
        'nurse': !exists(json, 'nurse') ? undefined : json['nurse'],
        'patient': !exists(json, 'patient') ? undefined : json['patient'],
        'rentID': !exists(json, 'rentID') ? undefined : json['rentID'],
        'room': !exists(json, 'room') ? undefined : json['room'],
    };
}

export function ControllersRentToJSON(value?: ControllersRent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'added': value.added,
        'kinName': value.kinName,
        'kinTel': value.kinTel,
        'nurse': value.nurse,
        'patient': value.patient,
        'rentID': value.rentID,
        'room': value.room,
    };
}


