/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDiagnose,
    EntDiagnoseFromJSON,
    EntDiagnoseFromJSONTyped,
    EntDiagnoseToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDiseaseEdges
 */
export interface EntDiseaseEdges {
    /**
     * DiseaseDiagnose holds the value of the disease_diagnose edge.
     * @type {Array<EntDiagnose>}
     * @memberof EntDiseaseEdges
     */
    diseaseDiagnose?: Array<EntDiagnose>;
}

export function EntDiseaseEdgesFromJSON(json: any): EntDiseaseEdges {
    return EntDiseaseEdgesFromJSONTyped(json, false);
}

export function EntDiseaseEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDiseaseEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'diseaseDiagnose': !exists(json, 'diseaseDiagnose') ? undefined : ((json['diseaseDiagnose'] as Array<any>).map(EntDiagnoseFromJSON)),
    };
}

export function EntDiseaseEdgesToJSON(value?: EntDiseaseEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'diseaseDiagnose': value.diseaseDiagnose === undefined ? undefined : ((value.diseaseDiagnose as Array<any>).map(EntDiagnoseToJSON)),
    };
}


