/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDepartment,
    EntDepartmentFromJSON,
    EntDepartmentFromJSONTyped,
    EntDepartmentToJSON,
    EntDisease,
    EntDiseaseFromJSON,
    EntDiseaseFromJSONTyped,
    EntDiseaseToJSON,
    EntDoctor,
    EntDoctorFromJSON,
    EntDoctorFromJSONTyped,
    EntDoctorToJSON,
    EntPatient,
    EntPatientFromJSON,
    EntPatientFromJSONTyped,
    EntPatientToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDiagnoseEdges
 */
export interface EntDiagnoseEdges {
    /**
     * 
     * @type {EntDepartment}
     * @memberof EntDiagnoseEdges
     */
    department?: EntDepartment;
    /**
     * 
     * @type {EntDisease}
     * @memberof EntDiagnoseEdges
     */
    disease?: EntDisease;
    /**
     * 
     * @type {EntDoctor}
     * @memberof EntDiagnoseEdges
     */
    doctor?: EntDoctor;
    /**
     * 
     * @type {EntPatient}
     * @memberof EntDiagnoseEdges
     */
    patient?: EntPatient;
}

export function EntDiagnoseEdgesFromJSON(json: any): EntDiagnoseEdges {
    return EntDiagnoseEdgesFromJSONTyped(json, false);
}

export function EntDiagnoseEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDiagnoseEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'department': !exists(json, 'department') ? undefined : EntDepartmentFromJSON(json['department']),
        'disease': !exists(json, 'disease') ? undefined : EntDiseaseFromJSON(json['disease']),
        'doctor': !exists(json, 'doctor') ? undefined : EntDoctorFromJSON(json['doctor']),
        'patient': !exists(json, 'patient') ? undefined : EntPatientFromJSON(json['patient']),
    };
}

export function EntDiagnoseEdgesToJSON(value?: EntDiagnoseEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'department': EntDepartmentToJSON(value.department),
        'disease': EntDiseaseToJSON(value.disease),
        'doctor': EntDoctorToJSON(value.doctor),
        'patient': EntPatientToJSON(value.patient),
    };
}


