/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDiagnoseEdges,
    EntDiagnoseEdgesFromJSON,
    EntDiagnoseEdgesFromJSONTyped,
    EntDiagnoseEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDiagnose
 */
export interface EntDiagnose {
    /**
     * 
     * @type {EntDiagnoseEdges}
     * @memberof EntDiagnose
     */
    edges?: EntDiagnoseEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntDiagnose
     */
    id?: number;
}

export function EntDiagnoseFromJSON(json: any): EntDiagnose {
    return EntDiagnoseFromJSONTyped(json, false);
}

export function EntDiagnoseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDiagnose {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntDiagnoseEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntDiagnoseToJSON(value?: EntDiagnose | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntDiagnoseEdgesToJSON(value.edges),
        'id': value.id,
    };
}


