/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntOperativerecord,
    EntOperativerecordFromJSON,
    EntOperativerecordFromJSONTyped,
    EntOperativerecordToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntExaminationroomEdges
 */
export interface EntExaminationroomEdges {
    /**
     * ExaminationroomOperativerecord holds the value of the Examinationroom_Operativerecord edge.
     * @type {Array<EntOperativerecord>}
     * @memberof EntExaminationroomEdges
     */
    examinationroomOperativerecord?: Array<EntOperativerecord>;
}

export function EntExaminationroomEdgesFromJSON(json: any): EntExaminationroomEdges {
    return EntExaminationroomEdgesFromJSONTyped(json, false);
}

export function EntExaminationroomEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntExaminationroomEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'examinationroomOperativerecord': !exists(json, 'examinationroomOperativerecord') ? undefined : ((json['examinationroomOperativerecord'] as Array<any>).map(EntOperativerecordFromJSON)),
    };
}

export function EntExaminationroomEdgesToJSON(value?: EntExaminationroomEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'examinationroomOperativerecord': value.examinationroomOperativerecord === undefined ? undefined : ((value.examinationroomOperativerecord as Array<any>).map(EntOperativerecordToJSON)),
    };
}


