/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntOperativerecord,
    EntOperativerecordFromJSON,
    EntOperativerecordFromJSONTyped,
    EntOperativerecordToJSON,
    EntPrescription,
    EntPrescriptionFromJSON,
    EntPrescriptionFromJSONTyped,
    EntPrescriptionToJSON,
    EntRent,
    EntRentFromJSON,
    EntRentFromJSONTyped,
    EntRentToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntNurseEdges
 */
export interface EntNurseEdges {
    /**
     * Fromnurse holds the value of the fromnurse edge.
     * @type {Array<EntRent>}
     * @memberof EntNurseEdges
     */
    fromnurse?: Array<EntRent>;
    /**
     * NurseOperativerecord holds the value of the Nurse_Operativerecord edge.
     * @type {Array<EntOperativerecord>}
     * @memberof EntNurseEdges
     */
    nurseOperativerecord?: Array<EntOperativerecord>;
    /**
     * NursePrescription holds the value of the nurse_prescription edge.
     * @type {Array<EntPrescription>}
     * @memberof EntNurseEdges
     */
    nursePrescription?: Array<EntPrescription>;
}

export function EntNurseEdgesFromJSON(json: any): EntNurseEdges {
    return EntNurseEdgesFromJSONTyped(json, false);
}

export function EntNurseEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntNurseEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fromnurse': !exists(json, 'fromnurse') ? undefined : ((json['fromnurse'] as Array<any>).map(EntRentFromJSON)),
        'nurseOperativerecord': !exists(json, 'nurseOperativerecord') ? undefined : ((json['nurseOperativerecord'] as Array<any>).map(EntOperativerecordFromJSON)),
        'nursePrescription': !exists(json, 'nursePrescription') ? undefined : ((json['nursePrescription'] as Array<any>).map(EntPrescriptionFromJSON)),
    };
}

export function EntNurseEdgesToJSON(value?: EntNurseEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fromnurse': value.fromnurse === undefined ? undefined : ((value.fromnurse as Array<any>).map(EntRentToJSON)),
        'nurseOperativerecord': value.nurseOperativerecord === undefined ? undefined : ((value.nurseOperativerecord as Array<any>).map(EntOperativerecordToJSON)),
        'nursePrescription': value.nursePrescription === undefined ? undefined : ((value.nursePrescription as Array<any>).map(EntPrescriptionToJSON)),
    };
}


