/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntNurse,
    EntNurseFromJSON,
    EntNurseFromJSONTyped,
    EntNurseToJSON,
    EntPatient,
    EntPatientFromJSON,
    EntPatientFromJSONTyped,
    EntPatientToJSON,
    EntRoom,
    EntRoomFromJSON,
    EntRoomFromJSONTyped,
    EntRoomToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRentEdges
 */
export interface EntRentEdges {
    /**
     * 
     * @type {EntNurse}
     * @memberof EntRentEdges
     */
    nurse?: EntNurse;
    /**
     * 
     * @type {EntPatient}
     * @memberof EntRentEdges
     */
    patient?: EntPatient;
    /**
     * 
     * @type {EntRoom}
     * @memberof EntRentEdges
     */
    room?: EntRoom;
}

export function EntRentEdgesFromJSON(json: any): EntRentEdges {
    return EntRentEdgesFromJSONTyped(json, false);
}

export function EntRentEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRentEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nurse': !exists(json, 'nurse') ? undefined : EntNurseFromJSON(json['nurse']),
        'patient': !exists(json, 'patient') ? undefined : EntPatientFromJSON(json['patient']),
        'room': !exists(json, 'room') ? undefined : EntRoomFromJSON(json['room']),
    };
}

export function EntRentEdgesToJSON(value?: EntRentEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nurse': EntNurseToJSON(value.nurse),
        'patient': EntPatientToJSON(value.patient),
        'room': EntRoomToJSON(value.room),
    };
}


