/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRentEdges,
    EntRentEdgesFromJSON,
    EntRentEdgesFromJSONTyped,
    EntRentEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRent
 */
export interface EntRent {
    /**
     * AddedTime holds the value of the "added_time" field.
     * @type {string}
     * @memberof EntRent
     */
    addedTime?: string;
    /**
     * 
     * @type {EntRentEdges}
     * @memberof EntRent
     */
    edges?: EntRentEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntRent
     */
    id?: number;
    /**
     * KinName holds the value of the "kin_name" field.
     * @type {string}
     * @memberof EntRent
     */
    kinName?: string;
    /**
     * KinTel holds the value of the "kin_tel" field.
     * @type {string}
     * @memberof EntRent
     */
    kinTel?: string;
    /**
     * 
     * @type {number}
     * @memberof EntRent
     */
    patientId?: number;
    /**
     * RentID holds the value of the "rent_id" field.
     * @type {string}
     * @memberof EntRent
     */
    rentId?: string;
}

export function EntRentFromJSON(json: any): EntRent {
    return EntRentFromJSONTyped(json, false);
}

export function EntRentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addedTime': !exists(json, 'added_time') ? undefined : json['added_time'],
        'edges': !exists(json, 'edges') ? undefined : EntRentEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'kinName': !exists(json, 'kin_name') ? undefined : json['kin_name'],
        'kinTel': !exists(json, 'kin_tel') ? undefined : json['kin_tel'],
        'patientId': !exists(json, 'patient_id') ? undefined : json['patient_id'],
        'rentId': !exists(json, 'rent_id') ? undefined : json['rent_id'],
    };
}

export function EntRentToJSON(value?: EntRent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'added_time': value.addedTime,
        'edges': EntRentEdgesToJSON(value.edges),
        'id': value.id,
        'kin_name': value.kinName,
        'kin_tel': value.kinTel,
        'patient_id': value.patientId,
        'rent_id': value.rentId,
    };
}


