// Code generated by entc, DO NOT EDIT.

package disease

const (
	// Label holds the string label denoting the disease type in the database.
	Label = "disease"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDiseaseName holds the string denoting the disease_name field in the database.
	FieldDiseaseName = "disease_name"

	// EdgeDiseaseDiagnose holds the string denoting the disease_diagnose edge name in mutations.
	EdgeDiseaseDiagnose = "disease_diagnose"

	// Table holds the table name of the disease in the database.
	Table = "diseases"
	// DiseaseDiagnoseTable is the table the holds the disease_diagnose relation/edge.
	DiseaseDiagnoseTable = "diagnoses"
	// DiseaseDiagnoseInverseTable is the table name for the Diagnose entity.
	// It exists in this package in order to avoid circular dependency with the "diagnose" package.
	DiseaseDiagnoseInverseTable = "diagnoses"
	// DiseaseDiagnoseColumn is the table column denoting the disease_diagnose relation/edge.
	DiseaseDiagnoseColumn = "disease_id"
)

// Columns holds all SQL columns for disease fields.
var Columns = []string{
	FieldID,
	FieldDiseaseName,
}

var (
	// DiseaseNameValidator is a validator for the "Disease_Name" field. It is called by the builders before save.
	DiseaseNameValidator func(string) error
)
